wandb_version: 1

device:
  desc: null
  value: cuda
timestamp:
  desc: null
  value: 2024-04-21_16-01-21
dataset_name:
  desc: null
  value: cifar10
task:
  desc: null
  value: clf
wandb_logs:
  desc: null
  value: true
trial:
  desc: null
  value: 0
Master_Model:
  desc: null
  value: Master_Model
epochs:
  desc: null
  value: 200
results_dict:
  desc: null
  value:
    train:
      train_accuracy: []
      train_loss: []
      train_loss_ce: []
      train_pred_loss: []
    test:
      test_accuracy: []
      test_loss: []
      test_loss_ce: []
      test_pred_loss: []
cifar10:
  desc: null
  value:
    batch_size: 128
    optimizer: torch.optim.sgd.SGD
    optim_p:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0005
cifar100:
  desc: null
  value:
    batch_size: 128
    optimizer: torch.optim.sgd.SGD
    optim_p:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0005
svhn:
  desc: null
  value:
    batch_size: 128
    optimizer: torch.optim.sgd.SGD
    optim_p:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0005
caltech256:
  desc: null
  value:
    batch_size: 64
    optimizer: torch.optim.sgd.SGD
    optim_p:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0005
tinyimagenet:
  desc: null
  value:
    batch_size: 128
    optimizer: torch.optim.sgd.SGD
    optim_p:
      lr: 0.001
      momentum: 0.9
      weight_decay: 0.0005
init_lab_obs:
  desc: null
  value: 2000
al_iters:
  desc: null
  value: 5
unlab_sample_dim:
  desc: null
  value: 10000
n_top_k_obs:
  desc: null
  value: 2000
strategy_name:
  desc: null
  value: ResNet_GTG_Module_GTG_mixed_corr_MEAN_threshold_0.5
iter:
  desc: null
  value: 1
LL:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713708090.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
